source "http://rubygems.org"

gem "crack"
gem "happymapper"
gem "nokogiri"
gem "nokogiri-happymapper"
gem "pivotal-tracker"
gem "redis"
gem "rest-client"
gem "sinatra"
gem "sinatra-contrib"
gem "thin"
gem "yajl-ruby"
gem "yaml"
