development:
  adapter: sqlite3                                                              
  database: /home/hu/projects/defekts/db/defekts.db                               
  pool: 5                                                                       
  timeout: 5000 

production:                                                                     
  adapter: postgresql
  encoding: utf8
  database: defekts
  username: root
  password: steve
