development:
  adapter: sqlite3
  database: $FILE_LOCATION
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: defects
  username: $USERNAME
  password: $PASSWORD

